baseURL = "https://staging.rochester2600.com"
languageCode = "en-us"
title = "Rochester 2600 | Rochester's hacking and infosec group"
theme = "navigator-hugo"
summaryLength = 500

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
#defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    logo = "images/logo.png"

    # Gestion des langues : FR / EN / NL / DE
    [[Params.listeLangues]]
    code = "en"
    
    # meta data
    author = "Themefisher"
    description = "Rochester, NY hacking and infosec community meetup"

# Gestion des langues : FR / EN / NL / DE
[Languages]


    ############# 2 - Site en ENGLISH
    [Languages.en]
    weight = 1
    languageCode = "en-us"
    title = "Rochester 2600"
    dateFormat = "January 2, 2006"

    home = "Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "We are a non-profit org made up of a group of hackers that like to chat about infosec stuff. We're professionals and we're amateurs. Come hang out."

# Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = true
        topTitle= "Latest meeting updates"
        title   = "Meetings"
        subtitle= "Look below for the latest information on meetings. Click on the meeting to see the list of presentations."

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "Rochester 2600"
        description = "Rochester's longest running hacking and information security meetup group. A community of locals interested in discussing security, sharing knowledge, and enjoying technology."
        button  = true
        btnText = "Next Meeting"
        #btnURL  = "#blog"
        videoThumb = "images/header_logo.png"
        #videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = false
        title   = "A community of people that happen to like security"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

    [Languages.en.params.community]
        enable  = true
        topTitle= "Latest meeting updates"
        title   = "Projects and Partners"
        description = "Here are a variety of projects and partners we're involved with:"    

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "Ways to stay involved"
        title   = "Getting Involved"
        subtitle= "If you're interested in finding out more, consider RSVP'ing to a meeting so we know how many people might show up. Follow us on Twitter for the latest updates. Hangout with some of us in the #security channel of RocDev."
        address = "14/05, Stockhome <br> Victori Palace , United States"
        #facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/roc2600"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = false
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2        
        
    [[menu.nav]]
        name    = "meetings"
        url     = 'meetings'
        weight  = 3
        

    [[menu.nav]]
        name    = "presentations"
        url     = "presentations"
        weight  = 4
        

    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 6
        

    [[menu.nav]]
        name    = "news"
        pre     = '<i class="fas fa-external-link-alt"></i>'
        url     = "https://links.rochester2600.com"
        weight  = 7
        


    # Community Links
    [[menu.community]]
        name    = "BSidesROC"
        url     = "https://www.bsidesroc.com"
        weight  = 1
        pre     = '<i class="fas fa-users"></i>'
    
    [[menu.community]]
        name    = "Hack Rochester"
        url     = "https://www.hackrochester.com"
        weight  = 2
        pre     = '<i class="fas fa-user-secret"></i>'

    [[menu.community]]
        name    = "Rochester ISSA"
        url     = "https://rocissa.org"
        weight  = 3
        pre     = '<i class="fas fa-user-lock"></i>'

    [[menu.community]]
        name    = "OWASP Rochester"
        url     = "https://www.owasp.org/index.php/Rochester"
        weight  = 4
        pre     = '<i class="fas fa-user-shield"></i>'

    [[menu.community]]
        name    = "RoCDev"
        url     = "https://rocdev.org"
        weight  = 5
        pre     = '<i class="fas fa-code"></i>'
    
