version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Run hugo"
          command: hugo 
      - persist_to_workspace:
          root: /home/circleci
             paths:
                - repo

