version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:latest
    working_cirectory: ~/project/
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: "Run hugo"
          command: hugo -v -s src -d public
      - persist_to_workspace:
          root: project
          paths:
             - public
  deploy:
    docker:
      - image: circleci/python:2
    working_directory: ~/project
    steps:
      #- checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "Pipfile" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-
      - attach_workspace:
          at: project

      - run: echo 'export PATH="$PATH:/home/circleci/.local/bin"' >> $BASH_ENV
      - run: cd ~/repo
      - run:
          name: fucking gsutil install
          command: |
            pip install gsutil --user

      - run:
          name: run deploy script
          command: |
            cd ~/project/tools
            echo $GCS | base64 -d > 2600.json
            ./deploy.sh
workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy:
          requires:
            - build
